const MessageConstant = {
    SUCCESS_CODE: 200,
    SUCCESS_MSG: 'SUCCESS',
    ERROR_CODE: 400,
    ERROR_MSG: 'FAILED',
    PAGE_NOT_FOUND_ERROR_CODE: 500,
    PAGE_NOT_FOUND_ERROR_MSG: 'PAGE_NOT_FOUND_ERROR',
    SUBJECT: "Your Account Is Registered..",
    TOKEN_ERROR_CODE: 401,
    TOKEN_ERROR_MSG: "USER HAS NOT AUTHORIZED",
    INVALID_TOKEN_CODE: 400,
    EXPIRE_TOKEN_MSG: "USER TOKEN IS EXPIRED",
    EXPIRE_TOKEN_CODE: 401,
    INVALID_TOKEN_MSG: "INVALID USER TOKEN",
    USER_NOT_CREATED: "User Not Created",
    USER_CREATED_SUCCESSFULLY: "User Created Successfully",
    USER_NOT_FOUND: "User Not Found",
    INVALID_EMAIL_OR_PASSWORD: "Invalid Email or Password",
    USER_GET_SUCCESSFULLY: "User Get Successfully..",
    USER_IS_NOT_GET: "User Is Not Get",
    USER_GET_BY_ID_SUCCESSFULLY: "User Get By Id Successfully..",
    USER_IS_NOT_GET_BY_ID: "User Is Not Get By Id",
    USER_IS_NOT_DELETE: "User Is Not Delete",
    USER_DELETE_SUCCESSFULLY: "User Delete Successfully..",
    USER_IS_NOT_UPDATE: "User Is Not Update",
    USER_UPDATE_SUCCESSFULLY: "User Update Successfully..",
    USER_IS_NOT_JOIN_ARRAY_ELEMENT: "User Is Not Join Array Element",
    USER_JOIN_ARRAY_ELEMENT_SUCCESSFULLY: "User Join Array Element Successfully..",
    USER_IS_NOT_LOGIN: "User Is Not Login",
    USER_LOGIN_SUCCESSFULLY: "User Login Successfully..",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    USER_READ_DATA_SUCCESSFULLY: "User Read Data Successfully..",
    USER_IS_NOT_READ_DATA: "User Is Not Read Data",
    USER_WRITE_DATA_SUCCESSFULLY: "User Write Data Successfully..",
    USER_READ_XLSXDATA_SUCCESSFULLY: "User Read XLSX Data Successfully..",
    USER_SEND_MAIL_SUCCESSFULLY: "User Send Mail Successfully..",
}
module.exports = MessageConstant